# Generated by Django 4.1.3 on 2022-12-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image_1',
            field=models.ImageField(blank=True, default='product_imgs/no-image.jpg', null=True, upload_to='product_imgs/', verbose_name='Картинка 1'),
        ),
    ]
