# Generated by Django 4.1.3 on 2022-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productvariant_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=400, verbose_name='ЧПУ'),
        ),
    ]
